### ISSUE TITLE
Is it possible to change singular row properties in a Table

### ISSUE THREAD

**Issue by jimbob88** [dddomodossola/remi#296]
So I have created a table using the following class:
```python
class MyTable(gui.Table):
	def __init__(self, **kwargs):
		super(MyTable, self).__init__(**kwargs)

	def on_table_row_click(self, row, item):
		column_index = 0
		for k in row.children.keys():
			v = row.children[k]
			if v==item:
				column_index = row._render_children_list.index(k)
		row_index = 0
		for k in self.children.keys():
			v = self.children[k]
			if v==row:
				row_index = self._render_children_list.index(k)
		print(row_index, self.__dict__.keys())
		# self.eventManager.propagate(self.EVENT_ON_TABLE_ROW_CLICK, (row,item,row_index,column_index))
```
Which is an extract from your `simple_table_app.py`
As a note eventManager is commented out due to the following error:
```
Traceback (most recent call last):
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.6/site-packages/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.6/site-packages/remi/gui.py", line 119, in __call__
    return self.callback(self.event_source_instance, *callback_params)
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.6/site-packages/remi/gui.py", line 119, in __call__
    return self.callback(self.event_source_instance, *callback_params)
  File "/media/james/Development/Programming/Python/beer_engine/remi/V1/untitled.py", line 23, in on_table_row_click
    self.eventManager.propagate(self.EVENT_ON_TABLE_ROW_CLICK, (row,item,row_index,column_index))
AttributeError: 'MyTable' object has no attribute 'eventManager'
```
I am not sure if the above code was intended to do the job I wish to do yet I can not get it to work on 2019.4.  So is it possible to change the look of the selected item (like what would happen in a listbox on selection), kind of like so:

![Peek 2019-05-02 18-42](https://user-images.githubusercontent.com/9913366/57095131-060b1180-6d0a-11e9-8a2c-407d9982c95d.gif)

Not sure if this has asked before as well but is it possible to force a header size?

**Comment by dddomodossola** [comment]
Hello @jimbob88 , look at this example may be useful 
```
import remi.gui as gui
from remi import start, App



class MyTable(gui.Table):
    @gui.decorate_event
    def on_table_row_click(self, row, item):
        if hasattr(self, "last_clicked_row"):
            del self.last_clicked_row.style['outline']
        self.last_clicked_row = row
        self.last_clicked_row.style['outline'] = "1px dotted red"
        return (row, item)

class Communicator(App):

    def __init__(self, *args):
        self.net_name = "Gellish semantic network"
        super(Communicator, self).__init__(*args)

    # Define the main window
    def main(self):
        print('Net name:', self.net_name)
        self.container = gui.VBox(margin='0px auto')
        self.container.set_size(600, 600)

        self.table = MyTable.new_from_list([('ID', 'First Name', 'Last Name'),
                                   ('101', 'Danny', 'Young'),
                                   ('102', 'Christine', 'Holand'),
                                   ('103', 'Lars', 'Gordon'),
                                   ('104', 'Roberto', 'Robitaille'),
                                   ('105', 'Maria', 'Papadopoulos')], width=300, height=200, margin='10px')
        self.table.on_table_row_click.connect(self.on_table_row_click)
        self.container.append(self.table)

        return self.container

    def on_table_row_click(self, emitter, row, item):
        print("selected %s"%(item.get_text()))


if __name__ == "__main__":
    start(Communicator)
```

**Comment by jimbob88** [comment]
Thank you so much! This exactly the idea I had in mind, Thanks so much for your support!

Now with relation to the added comment (sorry if you didn't see it) about forcing the size of the table items, it seems if you only have the header and 5 blanks (` [('','', '', '', '', '') for _ in range(5)]`) the header fills the whole room, do you know of any solution to fix this issue thanks again for all your help so far:

![](http://i.imgur.com/v4QJEFD.png)

**Comment by dddomodossola** [comment]
Hello @jimbob88 ,

you should not set an height value for the table and it will size correctly. Additionally you can set an height for each table row:

        self.table = gui.Table.new_from_list([('ID', 'First Name', 'Last Name'),
                                   ('105', 'Maria', 'Papadopoulos')], width=300, margin='10px')
        for c in self.table.children.values():
            c.style['height'] = '40px'

**Comment by jimbob88** [comment]
Thanks for all your help, REMI has been a terrific piece of software - probably the best web development system for python! Thanks again for all your help!

**Comment by dddomodossola** [comment]
Thank you too, you are welcome ;-)

**Comment by jimbob88** [comment]
This is extremely good for the moment, but is it possible to force a scrollbar onto the table/automatically add it. Thanks so much for all your help!!!

**Comment by jimbob88** [comment]
Sorry but is it also possible to get the index of the row as well?

**Comment by MikeTheWatchGuy** [comment]
REMI **_is_** the best web development system for python!   No probably needed there.

**Comment by dddomodossola** [comment]
@jimbob88 I received two notifications about you. You asked me about row index and scroll bars. I don't see that questions here. Have you deleted that questions? Have you solved that?

**Comment by jimbob88** [comment]
Yeah, sorry about that, for the scrollbars issue i simply placed the table inside a Widget box so it wouldn't resize automatically and for row index I used the code `[child[0] for child in self.children.items() if child[1] == row][0]`. I am encountering further issues with header sizing though, the header still resizes to fit the box when I wish it to stay at ~30px? Is there a solution for this?

**Comment by dddomodossola** [comment]
@jimbob88 can you show me an example code of the problem?

**Comment by jimbob88** [comment]
False alarm, the issue was I hadn't removed the height attribute from style.update (which was added when I used the editor)
