### ISSUE TITLE
[Bug - Regression problem ] Label Widget lost set_layout_orientation method.  Worked fine in 2020.1.  

### ISSUE THREAD

**Issue by PySimpleGUI** [dddomodossola/remi#362]
This code previously worked:
```
                element.Widget = remi.gui.Label(element.DisplayText)
                element.Widget.set_layout_orientation(True)
```

but after a recent Remi upgrade it crashes with this error

```
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GooeyGUI/PySimpleGUIWeb.py", line 5121, in setup_remi_window
    PackFormIntoFrame(window, master_widget, window)
  File "C:/Python/PycharmProjects/GooeyGUI/PySimpleGUIWeb.py", line 4206, in PackFormIntoFrame
    element.Widget.set_layout_orientation(True)
AttributeError: 'Label' object has no attribute 'set_layout_orientation'
```

**Comment by PySimpleGUI** [comment]
I found one of the places I may have picked up the usage of this call:
https://github.com/dddomodossola/remi/blob/6a7be6e468f948fba8ba39acacb70250d0fd7651/examples/minefield_app.py

When I try and run it, it also crashes when trying to use this `set_layout_orientation` method.  Fixing those errors didn't fix everything however as it also crashes complaining that an attribute `append` disappeared.

---------------------

Backwards compatibility as a policy.

I try not to upgrade my Remi installs nor any other underlying package, unless necessary.  

_Is it often that Remi releases are not backwards compatible?_  

If so then I need to start pinning PySimpleGUI releases to a specific Remi release and then not deviate from that until it can be thoroughly regression tested.  I don't want PySimpleGUI users to run into these errors as a result of upgrading their PySimpleGUI code which happens to also get the latest Remi code because PySimpleGUI isn't tied to a specific release of Remi at the moment.

**Comment by dddomodossola** [comment]
Hello @PySimpleGUI I always try to keep backward compatibility, but unfortunately sometimes it is not possible, please excuse me for this problem. The error you are getting is caused by an update where I decided to explictly distinguish between "containers" and "non containers" widgets. This caused the problem you are getting because the Label is not a container, it is illogical to append a widget to a label, and it is illogical to set layout orientation because it has no children widgets to arrange. 
Is the PySimpleGUIWeb version on github the most updated? If so I can fix it. How can I simulate the error?

**Comment by PySimpleGUI** [comment]
You don't need to do anything with PySimpleGUIWeb code!  I've got that handled.  Just tell me what I need to do (which you have.... remove the call).

I think I got the code from the Minesweeper game or some other Remi sample code.  I'm sure I wouldn't have come up with it myself.  The Minesweeper game now also crashes with the append not working. I don't know if that's going to affect my code yet or not.

Thanks for the quick response!  Nothing else needed at this time.

**Comment by dddomodossola** [comment]
The remi update is vast and different widgets were affected by changes. I suggest to:
- use Container in place of Widget in PSG
- search for *append* in PSG and verify it is used only for remi containers (Container, VBox, HBox, Svg, SvgGroup,  ListView, DropDown, Table, TableRow, TableItem, TabBox, Dialogs, Menu, MenuBar, MenuItem, TreeView, TreeItem, ) 
- search for *set_layout_orientation* in PSG and verify it only used for remi containers

**Comment by PySimpleGUI** [comment]
Looks like everything pretty much works.  I checked where I'm using append and they are all containers.  I don't use set_layout_orientation anywhere at the moment, but may want to use it in the future depending on how I port over the "element justification" feature for Columns.  

Thanks for the quick help!


![image](https://user-images.githubusercontent.com/46163555/74793627-dde7a180-528e-11ea-891b-0c582160b487.png)

**Comment by dddomodossola** [comment]
You are my priority Mike

**Comment by PySimpleGUI** [comment]
I just released version 0.36.0 of PySimpleGUIWeb.  I decided to "pin" it to the Remi release 2020.2.5.  I won't be getting the latest release of Remi this way which is a good and a bad thing.  I can't leave it open to picking up the latest Remi release as I'm not sure if it'll be compatible or not.  I'll get new Remi releases, test them, then change the setup.py file to allow the later version of Remi code.  

Are Remi releases posted somewhere that I can watch to see when you've made a new release?  I only need something that will trigger me to go try things out so I can make a new release that uses the newer Remi code.

There are a number of new features I still need to pull over to the PySimpleGUIWeb port.  One that I like from the last PySimpleGUI release is the ability to "print" to an Element.  It looks like a normal print statement, including the `end` and `sep` parameters, but also includes an element indicator and optional color settings.  This will enable someone to re-route their prints to anywhere they want without actually changing stdout.  There are a good number of Issues marked "Cross port needed" that will eventually make it over into this port :-)

**Comment by dddomodossola** [comment]
Hello @PySimpleGUI , I release remi on pypi and I create a new git tag. I don't know if github notifies users on new git tag. I can personally notify you on changes.
Do you have an example about the print on widgets?

**Comment by PySimpleGUI** [comment]
Here's some demo code to show the `print_to_element` capability that was added to the tkinter port. I have not cross-ported the code to the other PySimpleGUI ports yet.  I wanted to make sure it worked well for tkinter first.

One of the prints in this example uses the color parameter, which of course is not part of a normal print statement.  You can add the 2 line `print` function to any program that is using prints and it should route the output to the element (widget) you want it to go to.

```python
import PySimpleGUI as sg

# print = lambda *args, **kwargs: sg.print_to_element(window['-ML-'+sg.WRITE_ONLY_KEY], *args, **kwargs)

def print(*args, **kwargs):
   sg.print_to_element(window['-ML-'+sg.WRITE_ONLY_KEY], *args, **kwargs)

layout = [
            [sg.Multiline(size=(70,20), key='-ML-'+sg.WRITE_ONLY_KEY)],
            [sg.Button('Go')],
         ]

window = sg.Window('Stdout is rerouted test', layout)
i=0
while True:             # Event Loop
    i += 1
    event, values = window.read()
    print(event, values, end='')
    if event is None:
        break
    if event == 'Go':
        print('Here is the line that should be on the same line', text_color='red')

window.close()
```

**Comment by dddomodossola** [comment]
Thank you so much @PySimpleGUI 
I will look about its implementation and I will port it to PSGW.

**Comment by PySimpleGUI** [comment]
It's OK, I'll port it over.  There are a few other things I need to get into there too.  It won't be a big deal to port as the code uses the high level update.  The only thing I'm unsure about is if I've done anything with colors and multiline with Remi. I'll check on that.

**Comment by PySimpleGUI** [comment]
Oh, Matplotlib support... that's the next thing I want to get working with PySimpleGUIWeb.  I'll check the issue I filed on that to see where things are.

**Comment by dddomodossola** [comment]
> It's OK, I'll port it over. There are a few other things I need to get into there too. It won't be a big deal to port as the code uses the high level update. The only thing I'm unsure about is if I've done anything with colors and multiline with Remi. I'll check on that.

Do you mean you will implement print function by yourself?

**Comment by PySimpleGUI** [comment]
Yes, the `print_to_element` I'll port over myself as it's using high level PySimpleGUI  calls.

Here's the entire code for that function.  It relies on the Multiline Element's update method to do the work.


```python
def print_to_element(multiline_element, *args, end=None, sep=None, text_color=None, background_color=None):
    """
    Print like Python normally prints except route the output to a multline element and also add colors if desired

    :param multiline_element: (Multiline) The multiline element to be output to
    :param args: List[Any] The arguments to print
    :param end: (str) The end char to use just like print uses
    :param sep: (str) The separation character like print uses
    :param text_color: The color of the text
    :param background_color: The background color of the line
    """
    sepchar = sep if sep is not None else ' '
    endchar = end if end is not None else '\n'

    outstring = ''
    for arg in args:
        outstring += str(arg) + sepchar
    outstring += endchar
    multiline_element.update(outstring, append=True, text_color_for_value=text_color, background_color_for_value=background_color)
```

I'll move it over and try it out.

**Comment by PySimpleGUI** [comment]
Ah, I need some help perhaps with my multiline update.

I am able to set the text and background colors for a multiline element (built using the `TextInput` Widget).  What is needed to get the PySimpleGUIWeb port working like the tkinter version is the ability to set the text and background colors for individual characters rather than the entire wdiget.

You can see the parameter called `text_color_for_value` used.  This is different than the `text_color` parameter as that parameter sets the color for the entire widget.  I need to make one like this for Remi Widgets.

Is it possible to append onto the end of the existing data text that has different colors than the existing text?

**Comment by dddomodossola** [comment]
I can create something like this, a multiline text widget that accepts pieces of text with different colors, but I doubt it could be editable. Is it ok for you?

**Comment by PySimpleGUI** [comment]
It doesn't need to be editable as there's an "output only" version of the multiline.  It needs to be selectable/copyable.  That seems to be the bigger thing people do.  Many people use them for logging output and other output that they will perhaps copy and paste into something else.  

It needs the kinds of interfaces that allow appending and keeping the view scrolled to the end, two challenges you solved for me originally 👍
